[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "mne>=1.11.0",
    "numpy>=2.4.0",
    "requests>=2.32.5",
    "scipy>=1.16.3",
    "streamlit>=1.52.2",
]
